### ISSUE TITLE
Puzzle 130 

### ISSUE THREAD

**Issue by stantonhive** [Etayson/Server-Client-apps-for-Etarkangaroo#2]
I do not fully understand how the server part works, I would be very grateful for clarifications.
I have a server with a puzzle range of 130, users connect to it at xxx.xxx.xxx:8000. The question becomes, does the server automatically allocate search ranges? And how can I track progress on the server? to understand how much more I can connect players with a certain power. Etar, I will be very grateful for the detailed answer.

**Comment by stantonhive** [comment]
Here are my server settings: EtarkangarooServer.exe -port 8000 -checkdp -dp 32 -wi 3000 -beginrange 200000000000000000000000000000000 -endrange 3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -pub 03633CBE3EC02B9401C5EFFA144C5B4D22F87940259634858FC7E59B1C09937852
 Or do I need to manually send all the search ranges myself? Perhaps I do not fully understand the principle of distribution of work by the server itself.

**Comment by Etayson** [comment]
The server is engaged in transmitting information about the work to the client (range, DP size, public key and other parameters)
The server also receives working files from clients, which it combines into a single working file and keeps track of whether the required public key has been found.
You can observe the progress on server when merging working files, during the merging it will indicate how many DPs have already been found and other information.
For kangaroos, it is not required to distribute work. Each worker starts the path of their kangaroos from random positions and continues on their way. The server is designed to combine DP points from clients into a single file and find the public key in it.
Therefore, it is very important that clients continue the path of their kangaroos, and not start them again.
It is also important that the total number of kangaroos is constant during the entire work cycle.
Try to test on a small range first to understand how it works:
```
REM puzzle #85
SET dpsize=17
SET wi=300
SET beginrange=1000000000000000000000
SET endrange=1fffffffffffffffffffff
SET pub=0329c4574a4fd8c810b7e42a4b398882b381bcd85e40c6883712912d167c83e73a 
EtarkangarooServer.exe -dp %dpsize% -wi %wi% -beginrange %beginrange% -endrange %endrange% -pub %pub% -checkdp
pause
```

**Comment by stantonhive** [comment]
I just want to rent a large number of GPUs and connect them to the server. am I doing the right thing? Or is it better to rent one GPU separately and connect them to the server?

**Comment by stantonhive** [comment]
and an important criterion for tracking is DPs?

**Comment by Etayson** [comment]
First, as I said above, try to use the server in a small range with one rig of GPUs to understand how it works.
After you understand how it works, you can rent rigs if you want, but
**Note, the 129-bit range solution will require a lot of resources and time.**
Expected operation for puzzle #130 at least 2^65.55 op. 
Therefore, before starting anything, think carefully and consider whether it is worth it and whether you have enough resources for it. And don't forget that kangaroo is a probabilistic algorithm that can only tell you with some probability how many operations it takes to find the key. In fact, more or less operations may be required.

**Comment by stantonhive** [comment]
> First, as I said above, try to use the server in a small range with one rig of GPUs to understand how it works. After you understand how it works, you can rent rigs if you want, but **Note, the 129-bit range solution will require a lot of resources and time.** Expected operation for puzzle #130 at least 2^65.55 op. Therefore, before starting anything, think carefully and consider whether it is worth it and whether you have enough resources for it. And don't forget that kangaroo is a probabilistic algorithm that can only tell you with some probability how many operations it takes to find the key. In fact, more or less operations may be required.

Thanks for the detailed answer. I got all the answers to my questions. Yes, I have the ability to use a large number of GPUs, which is why I ask a bunch of ridiculous questions. Thank you for your answers, your patience has no limits)
